### ISSUE TITLE
Откуда взялись эти числа?

### ISSUE THREAD

**Issue by MLPForever** [KopanevAnatoliy/WB_parser#1]
Расскажите пожалуйста, откуда вы взяли эти "магические" числа вот в этом блоке кода.

` def get_server_number(self, value):
        """
        Выбор сервера
        """
        conditions = [143, 287, 431, 719, 1007, 1061, 1115, 1169, 1313, 1601, 1655, 1919]
        for condition in conditions:
            if value <= condition:
                return f"{conditions.index(condition) + 1:02}"
        return "13"`

Спасибо!

**Comment by KopanevAnatoliy** [comment]
Из js.
![image](https://github.com/KopanevAnatoliy/WB_parser/assets/112515741/a16dc94c-15da-4c32-993e-17e35dabb861)
